# Generated by Django 4.1 on 2022-09-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieWatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_watched', models.BooleanField(default=False)),
                ('judul', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('release_date', models.DateField()),
                ('review', models.URLField()),
            ],
        ),
    ]
